Version: 0.2

phases:
  install:
      runtime-versions:
        java: corretto11
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username rimple --password-stdin 613933213663.dkr.ecr.ap-southeast-2.amazonaws.com/
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn clean package
      - docker-compose up --no-start
      - docker tag spring-boot-monitoring-sample_app:latest 613933213663.dkr.ecr.ap-southeast-2.amazonaws.com/spring-boot-monitoring-sample_app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 613933213663.dkr.ecr.ap-southeast-2.amazonaws.com/spring-boot-monitoring-sample_app:latest
